name: desert-quest # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
title: Ice Battles Chronicles
summary: Rule icy realms and defend them!
description: Assemble frozen warriors, build an empire, and battle enemies to protect your icy fortress.
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  desert-quest:
    command: bin/desert-quest-bin
    extensions: [gnome]
    plugs:
      - network
      - unity7
      - network-status

layout:
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0

parts:
  desert-quest:
    plugin: dump
    source: .
    organize:
      desert-quest-bin: bin/
